require: rubocop-rspec

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Layout/LineLength:
  Max: 100

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NoExpectationExample:
  Exclude:
    - spec/*

Style/FrozenStringLiteralComment:
  Enabled: false
